### ISSUE TITLE
Howdy from ZeroCater

### ISSUE THREAD

**Issue by rfadams** [dfrankland/zerocater-node#1]
Just stumbled across this and shared it with the rest of the team. Project is off to a good start, nice work!

I'm the Head of Engineering here at ZeroCater. We are currently working on a more full-featured public API (with docs!). Would definitely be interested in hearing your thoughts on the current api and what you would be interested in seeing in the future. My email is robert at zerocater, ping me if interested.

**Comment by dfrankland** [comment]
I have sent an email over to you @rfadams. If anyone else has feedback on ZeroCater's API, feel free to drop a comment!
